In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
seaborn.set()
from sklearn.linear_model import LinearRegression


In [3]:
data=pd.read_csv('1.02. Multiple linear regression.csv')
data

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [5]:
x=data[['SAT','Rand 1,2,3']]
y=data['GPA']

In [7]:
reg=LinearRegression()
reg.fit(x,y)

LinearRegression()

In [8]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [9]:
reg.intercept_

0.29603261264909353

In [16]:
reg.score(x,y)

0.4066811952814282

## Formula for Adjusted R^2

R^2_(adj.)= 1 -(1-R^2)*\frac(n-1)(n-p-1)

In [20]:
x.shape

(84, 2)

In [21]:
adjusted_r2=1-(1-reg.score(x,y))*(84-1)/(84-2-1)

In [22]:
adjusted_r2

0.39203134825134

In [31]:
def calc_adjusted_r_squared(r_squared,n,p):
    adjusted_r_squared=1-(1-r_squared)*(n-1)/(n-p-1)
    return adjusted_r_squared

In [34]:
calc_adjusted_r_squared(reg.score(x,y),x.shape[0],x.shape[1])

0.39203134825134

# Feature Selection

In [35]:
from sklearn.feature_selection import f_regression

In [36]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [37]:
p_values=f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [38]:
p_values.round(3)

array([0.   , 0.676])

As we can see, the p_value of variable(predictor) Rand 1,2,3 is more than 0.05, so we can predict that it not relevant or un necessary for our model.

# Creating summary table

In [41]:
reg_summary=pd.DataFrame(x.columns.values,columns=['Variables(Features/Predictors)'])
reg_summary

Variables(Features/Predictors)
0                            SAT
1                     Rand 1,2,3

In [42]:
reg_summary['coefficients']=reg.coef_
reg_summary['p-values']=p_values.round(3)
reg_summary

Variables(Features/Predictors)  coefficients  p-values
0                            SAT      0.001654     0.000
1                     Rand 1,2,3     -0.008270     0.676